version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-ead-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:9000/api"
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: "storeclient"
      NEXT_PUBLIC_KEYCLOAK_CLIENT_SECRET: "4adI52UeB2Ifhv9fvlmH2VzIei36IsJW"
      NEXT_PUBLIC_KEYCLOAK_ISSUER: "http://localhost:8181/realms/store"
      NEXT_PUBLIC_KEYCLOAK_ADMIN_USERNAME: "admin@gmail.com"
      NEXT_PUBLIC_KEYCLOAK_ADMIN_PASSWORD: "admin"
      NEXT_PUBLIC_KEYCLOAK_URL: "http://localhost:8181/realms/store"
      NEXT_PUBLIC_KEYCLOAK_HOST_URL: "http://localhost:8181"
      NEXT_PUBLIC_KEYCLOAK_REALM: "store"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "6nJoEdU+Er9O73UnXTjIzYt5XsHx6cmtrMqDBuZrEbc="
